config/routes.rb
Rails.application.routes.draw do
  root to:  'static_pages#home'
  devise_for :users
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html

  resources :posts
  resources :pages
  
  get       '/share',    to: 'pages#show'
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/post.rb
class Post < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :text, presence: true, length: { maximum: 140 }
  attr_accessor :date_from, :date_to
  paginates_per 10
  
  def self.total_grouped_by_day(start)
    calories = where(created_at: start.beginning_of_day..Time.zone.now)
    calories = calories.group("date(created_at)")
    calories = calories.select("created_at, sum(calories_earned) as total_calories_earned,
                                sum(calories_lost) as total_calories_lost")
    calories = calories.group_by { |c| c.created_at.to_date }
  end
  
  def self.grouped_sumed_by_day(start)
    calories = where(created_at: start.beginning_of_day..Time.zone.now)
    data_calories = Hash.new
    calories.each do |cal|
      date = cal.created_at.to_date
      data_calories[date] = Hash.new if data_calories[date].nil?
      data_calories[date][:calories_earned] = 0 if data_calories[date][:calories_earned].nil? 
      data_calories[date][:calories_lost] = 0 if data_calories[date][:calories_lost].nil? 
      data_calories[date][:calories_earned] += cal.calories_earned
      data_calories[date][:calories_lost] += cal.calories_lost
    end
    return data_calories
  end
    
end

app/models/post_search.rb
class PostSearch 
  attr_reader :date_from, :date_to, :text
  
  def initialize(params)
    params ||= {}
    @date_from = parse_date(params[:date_from], 1.month.ago.to_date.to_s)
    @date_to = parse_date(params[:date_to], Date.tomorrow.to_date.to_s)
    @text = params[:text]
  end
  
  def scope(id)
    search = Post.all
    search = search.where('user_id = ?', id)
    search = search.where('created_at BETWEEN ? AND ?', @date_from, @date_to)
    search = search.where('text LIKE ?', "%#{@text}%")
    
  end
  
  private
    def parse_date (date_string, default)
      Date.parse(date_string)
    rescue ArgumentError, TypeError
      default 
    end
  
end

app/models/user.rb
class User < ApplicationRecord
  attr_accessor :share_token_plain
  has_many :posts
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  def send_share_email
    UserMailer.share_calories(self).deliver_now
  end
  
  def generate_token(column)
    
  end
  
  # Returns a random token.
  def User.new_token
    SecureRandom.urlsafe_base64
  end
  
  # Sets the password reset attributes.
  def create_share_digest
    self.share_token_plain = User.new_token
    update_attribute(:share_token,  Digest::MD5.hexdigest(share_token_plain))
    update_attribute(:share_sent_at, Time.zone.now)
  end

  # Sends password reset email.
  def send_password_reset_email
    UserMailer.password_reset(self).deliver_now
  end
  
  def authenticated?(remember_token)
    digest = self.send("remember_digest")
    return false if digest.nil?
    BCrypt::Password.new(digest).is_password?(remember_token)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
     protect_from_forgery with: :exception

     before_action :configure_permitted_parameters, if: :devise_controller?

     protected

          def configure_permitted_parameters
               devise_parameter_sanitizer.permit(:sign_up) { |u| u.permit(:name, :email, :password)}
               devise_parameter_sanitizer.permit(:account_update) { |u| u.permit(:name, :email, :password, :current_password)}
          end

end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  before_action :authenticate_user!, except: [:edit]
  def index
    @user = current_user
    @search = PostSearch.new(params[:search])
    @posts = @search.scope(current_user.id)
    @count = @posts.count
    @posts = @search.scope(current_user.id).page(params[:page])
    
    if params[:refresh].nil? 
      @refresh = "Off"
    else
      @refresh = params[:refresh]
    end
  end
  
  def create
    redirect_to root_path
    @user = current_user
    email=params[:email]
    @user.create_share_digest
    UserMailer.share_calories(email, current_user).deliver_now
    redirect_to pages_path
  end
  
  def edit
    id = params[:id]
    puts id
    share_token_digest = Digest::MD5.hexdigest(params[:id])
    puts share_token_digest
    @user = User.find_by_share_token!(share_token_digest)
  end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :set_post, only: [:show, :edit, :update, :destroy]
  before_action :authenticate_user!
  # GET /posts
  # GET /posts.json
  def index
    @user = current_user
    @posts = current_user.posts.page(params[:page])
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)
    @post.user = current_user
    respond_to do |format|
      if @post.save
        format.html { redirect_to @post, notice: 'Post was successfully created.' }
        format.json { render :show, status: :created, location: @post }
      else
        format.html { render :new }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post, notice: 'Post was successfully updated.' }
        format.json { render :show, status: :ok, location: @post }
      else
        format.html { render :edit }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to pages_url, notice: 'Post was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:calories_earned, :calories_lost, :text)
    end
end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
    if current_user
      redirect_to pages_path
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
  def calories_char_data
    start_date = 1.month.ago
    calories_earned_by_day = current_user.posts.grouped_sumed_by_day(start_date)
    
    puts   calories_earned_by_day
    (start_date.to_date..Date.today).map do |date|
      {
          created_at: date,
          calories_earned: calories_earned_by_day[date].try(:[], :calories_earned) || 0,
          calories_lost: calories_earned_by_day[date].try(:[], :calories_lost) || 0,
      }
    end
  end
  
end

app/helpers/posts_helper.rb
module PostsHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/layouts/_alerts.html.erb
<p class="notice"><%= notice %></p>
<p class="alert"><%= alert %></p>

app/views/layouts/_header.html.erb
<nav class="navbar" role="navigation" aria-label="main navigation">
      <div class="navbar-brand">
        <a class="navbar-item" href= <%= root_path %> >
          <img src="https://i.ibb.co/9bDCxH1/CALapp.png" width="100" height="35">
        </a>
    
        <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasicExample">
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
          <span aria-hidden="true"></span>
        </a>
      </div>

  <div id="navbarBasicExample" class="navbar-menu">
    <div class="navbar-start">
        <%= link_to 'Registers', pages_path, class: "navbar-item" %>
    </div>

    <div class="navbar-end">
      <div class="navbar-item">
        <div class="buttons">
          <% if current_user %>
            <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "button is-primary is-rounded" %>
          <% else %>
            <%= link_to 'Sign up', new_user_registration_path, class: "button is-primary is-rounded" %>
            <%= link_to 'Sign in', new_user_session_path, class: "button is-light" %>
          <% end %>  
        </div>
      </div>
    </div>
  </div>
</nav>


            

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Home" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, message| 
        if message_type == "alert"
           message_type = "danger"
        end
        if message_type == "notice"
           message_type = "success"
        end %>
        <div class="notification is-<%= message_type %>"><%= message %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>  
  </body>
</html>

app/views/layouts/devise.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Home" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="columns">
      <div class="column is-half is-offset-one-quarter big-margin-bottom">
        <div class="card">
          <div class="card-content">
            
            <% flash.each do |message_type, message| 
              if message_type == "alert"
                 message_type = "danger"
              end 
              if message_type == "notice"
                 message_type = "success"
              end %>
              <div class="notification is-<%= message_type %>"><%= message %></div>
            <% end %>
            
            <%= yield %>  
          </div>
        </div>
      </div>
    </div>
    
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/layouts/posts.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />

    <title><%= content_for?(:title) ? yield(:title) : "Home" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render 'layouts/header' %>
    <div class="columns">
      <div class="column is-half is-offset-one-quarter big-margin-bottom">
        <div class="card">
          <div class="card-content">
            
            <% flash.each do |message_type, message| 
              if message_type == "alert"
                 message_type = "danger"
              end 
              if message_type == "notice"
                 message_type = "success"
              end %>
              <div class="notification is-<%= message_type %>"><%= message %></div>
            <% end %>
            
            <%= yield %>  
          </div>
        </div>
      </div>
    </div>
    
    <%= debug(params) if Rails.env.development? %>
  </body>
</html>

app/views/pages/edit.html.erb
<h2 class = "title is-2">Calories consumption of <%= @user.name %></h2>
<em class = "title is-6">Last month</em>

<%= content_tag :div, "", id: "calories_chart", data: {posts: calories_char_data} %>

app/views/pages/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Hello Bulma!</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.7.5/css/bulma.min.css">
    <script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>
  </head>
  <body>
  <section class="section">
    <div class="container">
      <h1 class="title">
        Hello World
      </h1>
      <p class="subtitle">
        My first website with <strong>Bulma</strong>!
        <BR><BR>
        <%= link_to 'Sign up', new_user_registration_path, class: "button is-link is-rounded" %>
        <p>
          <strong>User:</strong>
          <%= @posts.first.user.name %>
        </p>
        <p>
          <strong>Calories earned:</strong>
          <%= @posts.first.calories_earned %>
        </p>
        <p>
          <strong>Calories lost:</strong>
          <%= @posts.first.calories_lost %>
        </p>
        <p>
          <strong>Text:</strong>
          <%= @posts.first.text %>
        </p>
        <p>
          <strong>Created at:</strong>
          <%= @posts.first.created_at.strftime('%D - %T') %>
        </p>

        <%= content_tag :div, "", id: "calories_chart", data: {posts: calories_char_data} %>

        <BR>                
        <p class="buttons">
          <%= link_to(share_path, class: "button") do %>
          <span class="icon">
              <i class="fas fa-share-alt"></i>
            </span>
            <span>Share</span>
          <% end %>
          <a class="button is-primary">
            <span class="icon">
              <i class="fab fa-twitter"></i>
            </span>
            <span>Twitter</span>
          </a>
          <a class="button is-success">
            <span class="icon is-small">
              <i class="fas fa-check"></i>
            </span>
            <span>Save</span>
          </a>
          <a class="button is-danger is-outlined">
            <span>Delete</span>
            <span class="icon is-small">
              <i class="fas fa-times"></i>
            </span>
          </a>
        </p>

      </p>
    </div>
  </section>
  </body>
</html>

app/views/pages/index.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

<% if @refresh == "On" %>
  <script>
    setTimeout(function(){
      location.reload();
    },10000); // 10000 milliseconds means 3 seconds.
  </script>    
<% end %>
    
<h2 class = "title is-2">Hi, <%= @user.name %> </h2>

<div class="buttons">
<%= link_to 'Add register', new_post_path, class: "button is-danger" %>
</div>

<h3 class = "title is-3">Your registers: (<%= @count %>) </h3>

<div class="row">
  <%= form_tag pages_path, method: :get do %>
    <%= label_tag(@search.date_from, "From: ") %>
    <%= date_field_tag 'search[date_from]', @search.date_from %>
    <%= label_tag(@search.date_from, "to: ") %>
    <%= date_field_tag 'search[date_to]', @search.date_to %>
    <%= label_tag(@search.text, "contains: ") %>
    <%= text_field_tag 'search[text]', @search.text %>
    <%= submit_tag "Search", class: "button is-primary is-rounded" %>
  <% end %>
</div>

<BR>

<table class="table">
  <thead>
    <tr>
      <th><abbr title="Calories earned">CE</abbr></th>
      <th><abbr title="Calories lost">CL</abbr></th>
      <th>Text</th>
      <th>Date</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.calories_earned %></td>
        <td><%= post.calories_lost %></td>
        <td><%= post.text %></td>
        <td><%= post.created_at.strftime('%d %B %Y - %T') %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @posts %>
<br>
<br>

<h3 class = "title is-3">Your daily records: </h3>
<em class = "title is-6">Last month</em>
<%= content_tag :div, "", id: "calories_chart", data: {posts: calories_char_data} 
%>

<BR>
<div class="buttons">
  <%= link_to(share_path, class: "button") do %>
  <span class="icon">
      <i class="fas fa-share-alt"></i>
    </span>
    <span>Share</span>
  <% end %>
</div>

<%= form_tag pages_path, method: :get do %>
  <% if @refresh == "Off" %>
    <%= hidden_field_tag(:refresh, "On") %>
    <%= submit_tag "Auto-refresh every 10 seconds", class: "button is-primary is-rounded" %>
  <% else %>
    <%= hidden_field_tag(:refresh, "Off") %>
    <%= submit_tag "Stop auto-refresh", class: "button is-primary is-rounded" %>
      
  <% end %>
<% end %>

app/views/pages/show.html.erb
<div class="columns">
      <div class="column is-half is-offset-one-quarter big-margin-bottom">
        <div class="card">
          <div class="card-content">
            <%= yield %>  
          

<h2 class="title is-2">Share to:</h2>
<hr>


<%= form_with(url: pages_path) do |f| %>
  <div class="field">
    <%= f.label :email, class: "label" %>
    <%= f.email_field :email, autofocus: true, autocomplete: "email", class: "input" %>
  </div>
  <div class="actions">
    <%= f.submit "Send", class: "button is-primary is-rounded is-fullwidth" %>
  </div>
<% end %>


</div>
        </div>
      </div>
    </div>

app/views/posts/_form.html.erb
<%= form_with(model: post, local: true) do |form| %>
  <% if post.errors.any? %>
    <div id="error_explanation">
      <div class="notification is-danger">
      <h2><%= pluralize(post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% post.errors.full_messages.each do |message| %>
      
        <li><%= message %></li>
      <% end %>
      </ul>
      </div>
    </div>
    <BR>
  <% end %>


  <div class="field">
    <%= form.label :calories_earned, class: "label" %>
    <%= form.text_field :calories_earned, id: :post_user_id, class: "input" %>
  </div>
  
  <div class="field", class: "label">
    <%= form.label :calories_lost, class: "label" %>
    <%= form.text_field :calories_lost, id: :post_user_id, class: "input" %>
  </div>
  
  <div class="field">
    <%= form.label :text, class: "label" %>
    <%= form.text_area :text, id: :post_user_id, class: "input" %>
  </div>

  <div class="actions">
    <%= form.submit "Create", class: "button is-primary is-rounded is-fullwidth" %>
  </div>
<% end %>

app/views/posts/edit.html.erb
<h2 class = "title is-2">Editing register</h2>
<hr>

<%= render 'form', post: @post %>

<div class="has-text-centered" >
  <div class="big-margin-top" >
    <%= link_to 'Show', @post %> |
    <%= link_to 'Back', pages_path %>
  </div>
</div>

app/views/posts/index.html.erb
<script defer src="https://use.fontawesome.com/releases/v5.3.1/js/all.js"></script>

<h2 class = "title is-2">Hi, <%= @user.name %> </h2>

<div class="buttons">
<%= link_to 'Add register', new_post_path, class: "button is-danger" %>
</div>

<h3 class = "title is-3">Your registers: </h3>

<table class="table">
  <thead>
    <tr>
      <th><abbr title="Calories earned">CE</abbr></th>
      <th><abbr title="Calories lost">CL</abbr></th>
      <th>Text</th>
      <th>Created_at</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.calories_earned %></td>
        <td><%= post.calories_lost %></td>
        <td><%= post.text %></td>
        <td><%= post.created_at.strftime('%D - %T') %></td>
        <td><%= link_to 'Show', post %></td>
        <td><%= link_to 'Edit', edit_post_path(post) %></td>
        <td><%= link_to 'Destroy', post, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<%= paginate @posts %>
<br>
<br>

<h3 class = "title is-3">Your daily records: </h3>
<%= content_tag :div, "", id: "calories_chart", data: {posts: calories_char_data} %>

<BR>
<div class="buttons">
  <%= link_to(share_path, class: "button") do %>
  <span class="icon">
      <i class="fas fa-share-alt"></i>
    </span>
    <span>Share</span>
  <% end %>
</div>

app/views/posts/new.html.erb
<h2 class= "title is-2">New register</h2>
<hr>

<%= render 'form', post: @post %>

<div class="has-text-centered" >
  <div class="big-margin-top" >
    <%= link_to 'Back', pages_path %>
  </div>
</div>

app/views/posts/show.html.erb
<h2 class = "title is-2">Register</h2>
<hr>

<p>
  <span class = "label">User</span>
  <%= @post.user.name %>
</p>

<p>
  <span class = "label">Calories earned</span>
  <span class="tag is-link"><%= @post.calories_earned %></span>
</p>

<p>
  <span class = "label">Calories lost</span>
  <span class="tag is-danger"><%= @post.calories_lost %></span>
</p>

<p>
  <span class = "label">Message</span>
  <div class="box">
    <%= @post.text %>
  </div>
</p>

<p>
  <span class = "label">Hora</span>
  <%= @post.created_at.strftime('%d %B %Y - %T') %>
</p>
  
  
  

<div class="has-text-centered" >
  <div class="big-margin-top" >
    <%= link_to 'Edit', edit_post_path(@post) %> |
    <%= link_to 'Back', pages_path %>
  </div>
</div>

app/views/shared/_error_messages.html.1.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="notification is-danger">
      The form contains <%= pluralize(@user.errors.count, "error") %>.
    </div>
    <ul>
    <% @user.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_pages/home.html.erb
<h1 class="title is-1 has-text-centered">Welcome to the Calories App</h1>

<p>Keep track of your daily calories</p>

<BR>
<div class="buttons">
  <% if current_user %>
    <%= link_to 'Sign out', destroy_user_session_path, method: :delete, class: "button is-primary is-rounded" %>
  <% else %>
    <%= link_to 'Sign up', new_user_registration_path, class: "button is-primary is-rounded" %>
    <%= link_to 'Sign in', new_user_session_path, class: "button is-light" %>
  <% end %>  
</div>